name: 'hyperio'
description: 'hyperio is program for help you, create server using dart with minimal dependencies and super easy for use'
version: '0.0.1'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/hyperio'
issue_tracker: 'https://github.com/azkadev/hyperio/issues'
documentation: 'https://github.com/azkadev/hyperio'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://www.patreon.com/c/azkadev'
  - 'https://opencollective.com/azkadev'
  - 'https://paypal.me/azkadev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  http: '>=1.3.0 <=5.0.0'
  mime: '^2.0.0'
  path: '>=1.9.0 <=5.1.0'
  web: ^1.1.1
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'